/*
Catch recovers from an error notification by continuing the sequence without
emitting the error but by switching to the catch ObservableInt to provide
items.

	Catch	http://reactivex.io/documentation/operators/catch.html
*/
package Catch

